export const KDOCS_ZOOM_SCREEN = [
  { label: 'Fit', value: 'Fit' },
  { label: '50%', value: 0.5 },
  { label: '75%', value: 0.75 },
  { label: '90%', value: 0.9 },
  { label: '100%', value: 1 },
  { label: '125%', value: 1.25 },
  { label: '150%', value: 1.5 },
  { label: '200%', value: 2 },
];

export const KDOCS_TEXT_TRANSFORM = [
  { label: 'Normal text', value: 'normal' },
  { label: 'Title', value: 'title' },
  { label: 'Subtitle', value: 'subtitle' },
  { label: 'Heading 1', value: 'heading1' },
  { label: 'Heading 2', value: 'heading2' },
  { label: 'Heading 3', value: 'heading3' },
  { label: 'Options', value: 'options' },
];

export const KDOCS_FONT_FAMILY = [
  { label: 'Alegreya', value: 'Alegreya' },
  { label: 'AMATIC SC', value: 'AMATIC SC' },
  { label: 'Arial', value: 'Arial' },
  { label: 'Bree Serif', value: 'Bree Serif' },
  { label: 'Calibri', value: 'Calibri' },
  { label: 'Cambria', value: 'Cambria' },
  { label: 'Caveat', value: 'Caveat' },
  { label: 'Comfortaa', value: 'Comfortaa' },
  { label: 'Courier New', value: 'Courier New' },
  { label: 'EB Garamond', value: 'EB Garamond' },
  { label: 'Lobster', value: 'Lobster' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Merriweather', value: 'Merriweather' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Nunito', value: 'Nunito' },
  { label: 'Oswald', value: 'Oswald' },
  { label: 'Pacifico', value: 'Pacifico' },
  { label: 'Permanent Marker', value: 'Permanent Marker' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Proxima Nova', value: 'Proxima Nova' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Roboto Mono', value: 'Roboto Mono' },
  { label: 'Spectral', value: 'Spectral' },
  { label: 'Times New Roman', value: 'Times New Roman' },
  { label: 'Ultra', value: 'Ultra' },
  { label: 'Varela Round', value: 'Varela Round' },
];

export const KDOCS_FONT_SIZE = [
  { label: 8, value: 8 },
  { label: 9, value: 9 },
  { label: 10, value: 10 },
  { label: 11, value: 11 },
  { label: 12, value: 12 },
  { label: 14, value: 14 },
  { label: 18, value: 18 },
  { label: 24, value: 24 },
  { label: 30, value: 30 },
  { label: 36, value: 36 },
  { label: 48, value: 48 },
  { label: 60, value: 60 },
  { label: 72, value: 72 },
  { label: 96, value: 96 },
];
